#!/bin/bash

set -e

if [ -z "$SKIP_BOOTSTRAP" ] && [ -d /etc/bootstrap.d ]; then
    run-parts -v --exit-on-error --regex '.*' /etc/bootstrap.d
    echo "Finished bootstrap."
fi

if [ "$1" != "bootstrap" ]; then
    /bin/servur $@
fi

